name: "Issue and PR stale management"
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  stale:
    uses: vyos/.github/.github/workflows/check-stale.yml@current
    secrets: inherit
