---
name: J2 Lint

on:
  pull_request:
    branches:
      - current
      - sagitta
      - equuleus
  workflow_dispatch:

permissions:
  pull-requests: write
  contents: read

jobs:
  j2lint:
    uses: vyos/.github/.github/workflows/lint-j2.yml@current
    secrets: inherit
